namespace GaoWare.DependencyInjection.Generator;

public sealed class GaoWareStringHelpers
{
    public static string AttributeStrings => """
                                      // <auto-generated/>
                                      using System;
                                      using Microsoft.Extensions.DependencyInjection;       
                                      
                                      namespace GaoWare.DependencyInjection.Attributes;
                                      
                                      #nullable enable
                                      [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
                                      internal class GenerateServiceRegistrationAttribute : Attribute
                                      {  
                                      }   
                                      
                                      [AttributeUsage(AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
                                      internal class RegisterInterfaceAttribute : Attribute
                                      { 
                                      } 
                                      
                                      [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                                      internal class RegisterServiceAttribute : Attribute
                                      {
                                          private readonly string? _serviceName = null;
                                          private readonly ServiceLifetime _serviceLifetime = ServiceLifetime.Scoped;
                                          private readonly Type? _interfaceType = null;
                                      
                                          
                                          public RegisterServiceAttribute(ServiceLifetime lifetime, string? serviceName = null, Type? interfaceType = null)
                                          {
                                              _serviceLifetime = lifetime;
                                              _serviceName = serviceName;
                                              _interfaceType = interfaceType;
                                          }
                                      
                                          public string? ServiceName => _serviceName;
                                          public ServiceLifetime Lifetime => _serviceLifetime;
                                          public Type? InterfaceType => _interfaceType;
                                      
                                      }
                                      #nullable disable
                                      """;
}